/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-12-06 12:31:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import user.UserDAO;
import jobType.JobTypeDAO;
import jobType.JobTypeDTO;
import review.ReviewDAO;
import review.ReviewDTO;
import java.util.ArrayList;
import java.net.URLEncoder;

public final class review_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("jobType.JobTypeDAO");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("review.ReviewDTO");
    _jspx_imports_classes.add("jobType.JobTypeDTO");
    _jspx_imports_classes.add("user.UserDAO");
    _jspx_imports_classes.add("review.ReviewDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("  <head>\r\n");
      out.write("\r\n");
      out.write("    <title>전문가 Expert 사이트</title>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <!-- 부트스트랩 CSS 추가하기 -->\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- 커스텀 CSS 추가하기 -->\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/custom.css\">\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");


	request.setCharacterEncoding("UTF-8");

	String reviewDivide = "전체";

	String searchType = "최신순";

	String search = "";

	int pageNumber = 0;

	if(request.getParameter("reviewDivide") != null) {

		reviewDivide = request.getParameter("reviewDivide");

	}

	if(request.getParameter("searchType") != null) {

		searchType = request.getParameter("searchType");

	}

	if(request.getParameter("search") != null) {

		search = request.getParameter("search");

	}

	if(request.getParameter("pageNumber") != null) {

		try {

			pageNumber = Integer.parseInt(request.getParameter("pageNumber"));

		} catch (Exception e) {

			System.out.println("검색 페이지 번호 오류");

		}

	}

	String userID = null;

	if(session.getAttribute("userID") != null) {

		userID = (String) session.getAttribute("userID");

	}

	if(userID == null) {

		PrintWriter script = response.getWriter();

		script.println("<script>");

		script.println("alert('로그인을 해주세요.');");

		script.println("location.href = 'userLogin.jsp'");

		script.println("</script>");

		script.close();	

	}

	boolean emailChecked = new UserDAO().getUserEmailChecked(userID);

	if(emailChecked == false) {

		PrintWriter script = response.getWriter();

		script.println("<script>");

		script.println("location.href = 'emailSendConfirm.jsp'");

		script.println("</script>");

		script.close();		

		return;

	}


      out.write("	\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"index.jsp\">전문가 Expert 사이트</a>\r\n");
      out.write("\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbar\">\r\n");
      out.write("\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\r\n");
      out.write("      </button>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbar\">\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("\r\n");
      out.write("            <a class=\"nav-link\" href=\"index.jsp\">메인</a>\r\n");
      out.write("\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("\r\n");
      out.write("            <a class=\"nav-link\" href=\"profile.jsp\">전문가</a>\r\n");
      out.write("          </li>\r\n");
      out.write("           <li class=\"nav-item active\">\r\n");
      out.write("\r\n");
      out.write("            <a class=\"nav-link\" href=\"review.jsp\">후기</a>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <li class=\"nav-item dropdown\">\r\n");
      out.write("\r\n");
      out.write("            <a class=\"nav-link dropdown-toggle\" id=\"dropdown\" data-toggle=\"dropdown\">\r\n");
      out.write("\r\n");
      out.write("              회원 관리\r\n");
      out.write("\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"dropdown-menu\" aria-labelledby=\"dropdown\">\r\n");
      out.write("\r\n");


	if(userID == null) {


      out.write("\r\n");
      out.write("\r\n");
      out.write("              <a class=\"dropdown-item\" href=\"userLogin.jsp\">로그인</a>\r\n");
      out.write("\r\n");
      out.write("              <a class=\"dropdown-item\" href=\"userRegister.jsp\">회원가입</a>\r\n");
      out.write("\r\n");


	} else {


      out.write("\r\n");
      out.write("\r\n");
      out.write("              <a class=\"dropdown-item\" href=\"userLogout.jsp\">로그아웃</a>\r\n");
      out.write("\r\n");


	}


      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"./review.jsp\" method=\"get\" class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("\r\n");
      out.write("          <input type=\"text\" name=\"search\" class=\"form-control mr-sm-2\" placeholder=\"내용을 입력하세요.\">\r\n");
      out.write("\r\n");
      out.write("          <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">검색</button>\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("      <form method=\"get\" action=\"./review.jsp\" class=\"form-inline mt-3\">\r\n");
      out.write("\r\n");
      out.write("		<select name = \"jobType\" class=\"form-control mx-1 mt-2\">\r\n");
      out.write("		");

			JobTypeDAO jobTypeDAO = new JobTypeDAO();
			ArrayList<JobTypeDTO> list = jobTypeDAO.getList();
			for(int i = 0; i < list.size(); i++){
		
      out.write("\r\n");
      out.write("			<option value = ");
      out.print(list.get(i).getJobType() );
      out.write(">\r\n");
      out.write("			");
      out.print(list.get(i).getJobType() );
      out.write("\r\n");
      out.write("			</option>\r\n");
      out.write("		");

			}
		
      out.write("\r\n");
      out.write("		</select>\r\n");
      out.write("        <select name=\"searchType\" class=\"form-control mx-1 mt-2\">\r\n");
      out.write("\r\n");
      out.write("          <option value=\"최신순\">최신순</option>\r\n");
      out.write("\r\n");
      out.write("          <option value=\"추천순\" ");
if(searchType.equals("추천순")) out.println("selected");
      out.write(">추천순</option>\r\n");
      out.write("\r\n");
      out.write("        </select>\r\n");
      out.write("\r\n");
      out.write("        <input type=\"text\" name=\"search\" class=\"form-control mx-1 mt-2\" value=\"");
      out.print( search );
      out.write("\" placeholder=\"내용을 입력하세요.\">\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-primary mx-1 mt-2\">검색</button>\r\n");
      out.write("\r\n");
      out.write("        <a class=\"btn btn-primary mx-1 mt-2\" data-toggle=\"modal\" href=\"#registerModal\">등록하기</a>\r\n");
      out.write("\r\n");
      out.write("        <a class=\"btn btn-danger ml-1 mt-2\" data-toggle=\"modal\" href=\"#reportModal\">신고</a>\r\n");
      out.write("\r\n");
      out.write("      </form>\r\n");
      out.write("\r\n");


	ArrayList<ReviewDTO> reviewList = new ArrayList<ReviewDTO>();

	reviewList = new ReviewDAO().getList(reviewDivide, searchType, search, pageNumber);

	if(reviewList != null)

	for(int i = 0; i < reviewList.size(); i++) {

		if(i == 5) break;

		ReviewDTO review = reviewList.get(i);


      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div class=\"card bg-light mt-3\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-header bg-light\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-8 text-left\"><small>");
      out.print(review.getExpertName());
      out.write("</small></div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-4 text-right\">\r\n");
      out.write("\r\n");
      out.write("              종합 <span style=\"color: red;\">");
      out.print(review.getTotalScore());
      out.write("</span>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("          <h5 class=\"card-title\">\r\n");
      out.write("\r\n");
      out.write("            ");
      out.print(review.getReviewTitle());
      out.write("&nbsp;<small></small>\r\n");
      out.write("\r\n");
      out.write("          </h5>\r\n");
      out.write("\r\n");
      out.write("          <p class=\"card-text\">");
      out.print(review.getReviewContent());
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-9 text-left\">\r\n");
      out.write("\r\n");
      out.write("              시간 준수 <span style=\"color: red;\">");
      out.print(review.getTimeScore());
      out.write("</span>\r\n");
      out.write("\r\n");
      out.write("              친절도 <span style=\"color: red;\">");
      out.print(review.getComfortableScore());
      out.write("</span>\r\n");
      out.write("\r\n");
      out.write("              재상담 의사 <span style=\"color: red;\">");
      out.print(review.getReviewScore());
      out.write("</span>\r\n");
      out.write("\r\n");
      out.write("              <span style=\"color: green;\">(추천: ");
      out.print(review.getLikeCount());
      out.write(")</span>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-3 text-right\">\r\n");
      out.write("\r\n");
      out.write("              <a onclick=\"return confirm('추천하시겠습니까?')\" href=\"./likeAction.jsp?reviewID=");
      out.print(review.getReviewID());
      out.write("\">추천</a>\r\n");
      out.write("\r\n");
      out.write("              <a onclick=\"return confirm('삭제하시겠습니까?')\" href=\"./deleteAction.jsp?reviewID=");
      out.print(review.getReviewID());
      out.write("\">삭제</a>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");


	}


      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <ul class=\"pagination justify-content-center mt-3\">\r\n");
      out.write("\r\n");
      out.write("      <li class=\"page-item\">\r\n");
      out.write("\r\n");


	if(pageNumber <= 0) {


      out.write("     \r\n");
      out.write("\r\n");
      out.write("        <a class=\"page-link disabled\">이전</a>\r\n");
      out.write("\r\n");


	} else {


      out.write("\r\n");
      out.write("\r\n");
      out.write("		<a class=\"page-link\" href=\"./review.jsp?reviewDivide=");
      out.print(URLEncoder.encode(reviewDivide, "UTF-8"));
      out.write("&searchType=");
      out.print(URLEncoder.encode(searchType, "UTF-8"));
      out.write("&search=");
      out.print(URLEncoder.encode(search, "UTF-8"));
      out.write("&pageNumber=");
      out.print(pageNumber - 1);
      out.write("\">이전</a>\r\n");
      out.write("\r\n");


	}


      out.write("\r\n");
      out.write("\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("      <li class=\"page-item\">\r\n");
      out.write("\r\n");


	if(reviewList.size() < 6) {


      out.write("     \r\n");
      out.write("\r\n");
      out.write("        <a class=\"page-link disabled\">다음</a>\r\n");
      out.write("\r\n");


	} else {


      out.write("\r\n");
      out.write("\r\n");
      out.write("		<a class=\"page-link\" href=\"./review.jsp?reviewDivide=");
      out.print(URLEncoder.encode(reviewDivide, "UTF-8"));
      out.write("&searchType=");
      out.print(URLEncoder.encode(searchType, "UTF-8"));
      out.write("&search=");
      out.print(URLEncoder.encode(search, "UTF-8"));
      out.write("&pageNumber=");
      out.print(pageNumber + 1);
      out.write("\">다음</a>\r\n");
      out.write("\r\n");


	}


      out.write("\r\n");
      out.write("\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"modal fade\" id=\"registerModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modal\" aria-hidden=\"true\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"modal-header\">\r\n");
      out.write("\r\n");
      out.write("            <h5 class=\"modal-title\" id=\"modal\">리뷰 등록</h5>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\r\n");
      out.write("              <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("            <form action=\"./reviewRegisterAction.jsp\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("                  <label>전문가 이름</label>\r\n");
      out.write("\r\n");
      out.write("                  <input type=\"text\" name=\"expertName\" class=\"form-control\" maxlength=\"20\">\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group col-sm-4\">\r\n");
      out.write("\r\n");
      out.write("                  <label>전문가 상담 시간</label>\r\n");
      out.write("\r\n");
      out.write("                  <select name=\"timeDivide\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("                    <option name=\"오전\" selected>오전</option>\r\n");
      out.write("\r\n");
      out.write("                    <option name=\"점심\">점심</option>\r\n");
      out.write("\r\n");
      out.write("                    <option name=\"오후\">오후</option>\r\n");
      out.write("\r\n");
      out.write("                    <option name=\"저녁\">저녁</option>\r\n");
      out.write("\r\n");
      out.write("                  </select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group col-sm-4\">\r\n");
      out.write("\r\n");
      out.write("                  <label>예약 구분</label>\r\n");
      out.write("\r\n");
      out.write("                  <select name=\"reviewDivide\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("                    <option name=\"예약상담\" selected>예약상담</option>\r\n");
      out.write("\r\n");
      out.write("                    <option name=\"기타상담\">기타상담</option>\r\n");
      out.write("\r\n");
      out.write("                  </select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                <label>제목</label>\r\n");
      out.write("\r\n");
      out.write("                <input type=\"text\" name=\"reviewTitle\" class=\"form-control\" maxlength=\"20\">\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                <label>내용</label>\r\n");
      out.write("\r\n");
      out.write("                <textarea type=\"text\" name=\"reviewContent\" class=\"form-control\" maxlength=\"2048\" style=\"height: 180px;\"></textarea>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group col-sm-3\">\r\n");
      out.write("\r\n");
      out.write("                  <label>종합</label>\r\n");
      out.write("\r\n");
      out.write("                  <select name=\"totalScore\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"5\" selected>5</option>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"4\">4</option>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"3\">3</option>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"2\">2</option>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"1\">1</option>\r\n");
      out.write("\r\n");
      out.write("                  </select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group col-sm-3\">\r\n");
      out.write("\r\n");
      out.write("                  <label>시간 준수</label>\r\n");
      out.write("\r\n");
      out.write("                  <select name=\"timeScore\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"5\" selected>5</option>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"4\">4</option>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"3\">3</option>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"2\">2</option>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"1\">1</option>\r\n");
      out.write("\r\n");
      out.write("                  </select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group col-sm-3\">\r\n");
      out.write("\r\n");
      out.write("                  <label>친절도</label>\r\n");
      out.write("\r\n");
      out.write("                  <select name=\"comfortableScore\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"5\" selected>5</option>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"4\">4</option>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"3\">3</option>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"2\">2</option>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"1\">1</option>\r\n");
      out.write("\r\n");
      out.write("                  </select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group col-sm-3\">\r\n");
      out.write("\r\n");
      out.write("                  <label>재 상담 의사</label>\r\n");
      out.write("\r\n");
      out.write("                  <select name=\"reviewScore\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"5\" selected>5</option>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"4\">4</option>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"3\">3</option>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"2\">2</option>\r\n");
      out.write("\r\n");
      out.write("                    <option value=\"1\">1</option>\r\n");
      out.write("\r\n");
      out.write("                  </select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"modal-footer\">\r\n");
      out.write("\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">취소</button>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\">등록하기</button>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"modal fade\" id=\"reportModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modal\" aria-hidden=\"true\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"modal-header\">\r\n");
      out.write("\r\n");
      out.write("            <h5 class=\"modal-title\" id=\"modal\">신고하기</h5>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\r\n");
      out.write("              <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("            <form method=\"post\" action=\"./reportAction.jsp\">\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                <label>신고 제목</label>\r\n");
      out.write("\r\n");
      out.write("                <input type=\"text\" name=\"reportTitle\" class=\"form-control\" maxlength=\"20\">\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("                <label>신고 내용</label>\r\n");
      out.write("\r\n");
      out.write("                <textarea type=\"text\" name=\"reportContent\" class=\"form-control\" maxlength=\"2048\" style=\"height: 180px;\"></textarea>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"modal-footer\">\r\n");
      out.write("\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">취소</button>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-danger\">신고하기</button>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"bg-dark mt-4 p-5 text-center\" style=\"color: #FFFFFF;\">\r\n");
      out.write("\r\n");
      out.write("      Copyright ⓒ2021 전동준 All Rights Reserved.\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <!-- 제이쿼리 자바스크립트 추가하기 -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Popper 자바스크립트 추가하기 -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./js/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- 부트스트랩 자바스크립트 추가하기 -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
